language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml

script:
  ./vendor/bin/phpunit